### ISSUE TITLE
Gif of cow with hair in the wind is broken

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cow#120]
See readme:

![image](https://user-images.githubusercontent.com/5170590/52215036-40e4e100-28a4-11e9-9512-2394babd64bd.png)

I miss the windswept cow. 

Potential replacement: https://giphy.com/gifs/blow-screen-8AsXV477ls6LS

**Comment by chillu** [comment]
How is this not `impact/critical`?! :D

**Comment by robbieaverill** [comment]
Yeah it's pretty annoying. I've been working around it locally with this patch, which seems to help:

```diff
- ![moo](https://media.giphy.com/media/A5pcWMMIEO95S/giphy.gif)
+ ![moo](https://giphy.com/gifs/blow-screen-8AsXV477ls6LS)
```

**Comment by chillu** [comment]
https://github.com/silverstripe/cow/commit/d200a6247b383f5a115d3104cd79c8ddbb732060
