### ISSUE TITLE
If selected module release version already exists, cow should checkout that tag

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cow#130]
Scenario:

* Create a new release
* Set all modules to pre-existing versions (e.g. from the last release)
* Bump one module to be a new patch release version

In this case we're only release one patch version of one module, the others are all the same as the previous release. It would be great if cow would go through and checkout the existing tags in git for each module you're not releasing a new version for.

Current behaviour is that cow leaves these modules on e.g. `1.0` branch, so while we're saying 1.0.5 rather than whatever is newer than that in the plan, we're actually testing new changes.

Important because we need to test the release in a way that represents the final release, and we'd otherwise have to do this manually.

I realise that it would be better to do it with composer, but we don't necessarily want to change `1.0.x-dev` to `1.0.5` for a module in the composer dependencies (at least that shouldn't be committed in).

We could either do it with composer.json rewriting and composer update, or `cd module && git checkout [existingtag]`

**Comment by dnsl48** [comment]
Could be solved by https://github.com/silverstripe/cow/issues/153

**Comment by Cheddam** [comment]
The command introduced by #153 does indeed do this, and our current processes don't really call for it at this point (we base our regression testing on projects targeting unstable recipe tags, rather than the related Cow release folder.)
