### ISSUE TITLE
When adding a new module to recipes cow should include all its commits in the changelog generation

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cow#135]
When adding a new module to recipes, it won't have a prior version, because none were tagged. This means that cow doesn't include any commits from the new module in changelogs.

I'm not sure what the best solution here is, but maybe allow setting "None" as a prior version option, which would tell cow to look back to the beginning of time in that module when generating a changelog for the recipe.

*Clarification:* "all its commits" -> anything with a Cow tag prefix e.g. NEW, FIX etc, _or_ all commits if using `--include-other-changes` as an argument

**Comment by robbieaverill** [comment]
A workaround is to tag the initial commit in the local release as 0.0.1 and use that as the prior version in the changelog

**Comment by Cheddam** [comment]
We hit this infrequently enough that I'd wager the workaround is sufficient, so I'm going to close this out for now.
