### ISSUE TITLE
release:archive is allegedly including VCS history

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cow#136]
Some of our friends in the open source community have reported that the downloadable archive for 4.3.1 is around 300mb, which includes VCS history.

Cow should automatically exclude this - we may need to investigate why this has happened.

It was also reported that 4.3.1's archive is tied to PHP 7.1. We fixed this in #65 recently, so perhaps the releaser's cow version was not up-to-date.

**Comment by chillu** [comment]
We no longer do archive releases, hooray!
