### ISSUE TITLE
Add option to group changes by module in changelog generation

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cow#139]
It'd be cool to be able to group changes by module in the changelogs we generate, especially for massive changelogs like in CWP releases.

cc @chillu @scopeynz

**Comment by brynwhyman** [comment]
+1. How far would you go with granularity here? There's been mention of spitting by recipe as opposed to splitting by individual module which could strike a good balance if this is coupled with #184

**Comment by dnsl48** [comment]
Here are some examples of splitting by module/library:
  - Option A (plain): https://gist.github.com/dnsl48/946e812827c06ce2c14548c63c1023ce
  - Option B (tables): https://gist.github.com/dnsl48/f69d1c007566729a65f2ab174403bfae

I didn't prototype splitting by recipe yet, but I guess should be easy enough to do.
