### ISSUE TITLE
We don't have the ability to use a consistent version on Transifex - causing syntax markup differences

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/cow#146]
## The issue
E.g. https://github.com/silverstripe/silverstripe-framework/commit/fc63ac8fed8587714000c1a37bf7331a34818614#diff-8eff9e0de4d3e7e3184cac847cffd119R92

Sometimes it seems to be changing quotation around strings even when string values don't change at all.

## The cause
Depending on a local dev set-up, people may install different versions of Transefix, based on the dependancies it defines. 

## Solution options
a). Update the newly created Docker container to enforce a consistent version of Transifex. See recent PR: https://github.com/silverstripe/cow/pull/149

b). Perhaps we just need to update the release documentation that a pre-set up process is to have the same version of Python and ensure Transefix is up to date, which Transefix relies on.

**Comment by robbieaverill** [comment]
It's possible that this happens when two different farmers have different Transifex CLI versions, perhaps?

**Comment by dnsl48** [comment]
Yeah, I've just updated transifex-client dependencies and the issue seems to have disappeared

**Comment by maxime-rainville** [comment]
I'm thinking maybe we should add some sort of pre-step that checks that you have a compatible version of all required third party tools. Basically, if you don't have the correct version of python or PHP or transifex, then we block you right away from proceeding.

**Comment by dnsl48** [comment]
That implies we'll have to maintain that list of _compatible versions_ and update it when security releases come out. Furthermore, if you have a native setup, those could be upgraded by your package-manager or prevent you from upgrading your operating system in case you pin them down to the particular versions.

**Comment by maxime-rainville** [comment]
My perception of it is perhaps a little less expansive. I wouldn't lock people down to specific versions or flag insecure version of dependencies ... I don't think that's cow's purpose. I would mostly focus on defining what the minimal required versions are.

It would have been helpful for me getting cow set up locally if it warn me straight away of what I was missing.

Also for people running this thing natively, they are relatively easy way to switch between version of different binaries. e.g.: Ubuntu ships with Python 2.7 and Python 3.6, and you can pretty easily swap between the two with some clever use of alias.

At the end of the day if we know for a fact that cow doesn't work with specific version of some dependencies, then we should make a reasonable effort to try to warn users about it. Or maybe we just need to bite the bullet and say that you have to run this thing in a docker image like you suggested.

**Comment by dnsl48** [comment]
> I wouldn't lock people down to specific versions or flag insecure version of dependencies ... I would mostly focus on defining what the minimal required versions are.

In that case, we won't solve the issue reported in this card since the problem caused by the transifex dependencies installed with a time difference in several months

> At the end of the day if we know for a fact that cow doesn't work with specific version of some dependencies

it does work in both cases, but produces slightly different artefacts (semantically correct in both cases, but syntactically different)

> It would have been helpful for me getting cow set up locally if it warn me straight away of what I was missing

Agree, I think we might add a checker for those tools to be installed, but that feels to be a different problem since it happens with transifex-client installed and functioning well in both cases

**Comment by robbieaverill** [comment]
You're talking about using Docker for cow now right, so we _can_ have a consistent Transifex CLI version if we do that?

**Comment by dnsl48** [comment]
yes, I think in that case we might be able. That could imply us baking the image and publishing it to the hub. However, at the moment it always installs the freshest versions of everything on every localhost first time the container is getting build.

**Comment by brynwhyman** [comment]
Yeah, we striked-out the Docker option for this issue because it seems over-kill just to resolve this issue. Although, now that @dnsl48 already has the Docker PR ready we could shift the focus of this issue to make some explicit Transifex config updates to the container. Otherwise we're still going to see the same problem with individual containers being set up at different times.

The outcome of this issue is that everyone uses a consistent version of Transifex (not a minimum version) so to avoid syntax differences between versions.

**Comment by brynwhyman** [comment]
Given the above, I'm opening back up the Docker option. Here's the changes to the description:
> Solution options
```diff
- a). It seems difficult to pin all local development environments to use the same version, aside from creating something like a Docker image.
+ a). Update the newly created Docker container to enforce a consistent version of Transifex. See recent PR: https://github.com/silverstripe/cow/pull/149
```
