### ISSUE TITLE
Read composer.json from prior releases to determine prior releases of child modules

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cow#148]
## User story
As a developer doing a release plan, I want to have the prior versions of child modules specified, so that I do not have to manually review the prior release to see what the previous version was.

## ACs
- [x] When preparing a release plan, the prior version is pre-populated by Cow based on what was previously released
- [x] When I want to tie the base tag to a version that is not the latest release, the prior versions of that release can still be determined automatically 
- [x] It is still possible to customise/ manually update the value that is populated by default

## Notes
- There is a WIP PR: https://github.com/silverstripe/cow/pull/143
- This is less relevant for the core releases which have every recipe in lock-step

**Comment by robbieaverill** [comment]
Just a note, make sure you can still customise the value that is populated by default

**Comment by brynwhyman** [comment]
Serge would like to review

**Comment by brynwhyman** [comment]
Thanks for calling that out @robbieaverill. I've added the following AC, which I presume is more of a 'check' than bringing in additional work:

> - [ ] It is still possible to customise/ manually update the value that is populated by default
