### ISSUE TITLE
Add a step to build an archive for external audit

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/cow#151]
This is to make things simpler to create the archive that's sent for external auditing (currently by Insomnia)

The archive should follow the conventions:
 - `--prefer-dist`
 - exclude all source control files
 - exclude the `.env` file
 - Include the changelog containing all changes (upgrade-only dependencies must be included as well)
 - zip format

## Notes
- There has been some code in cow (since deleted) which used to archive the output to S3. So we can have a look at that for an initial reference.
- Also, look at the CWP release documentation which outlines how the release needs to be built before sending to Insomnia.

**Comment by maxime-rainville** [comment]
Doc has been updated to cover this.
