### ISSUE TITLE
Implement "release:checkout-tagged-base" command

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/cow#153]
## Summary

`release:checkout-tagged-base` command should go through all the modules and check out the common base commit between `current branch` and `previous tagged` version.

## Reasoning

That command would allow us to operate already released versions adding some hand-picked patches on top of it, rather than working with everything committed into minor branches since the last release.

E.g. `4.5.0-RC1` contains the recipe we want to take and add a single critical patch, rather than using everything from the `4.5.x-dev` branches.

To achieve that we could use `git merge-base` for tag and branch.

**Comment by ScopeyNZ** [comment]
Doesn't `composer create-project silverstripe/installer 4.5.0-rc1 4.5.0-rc1 --prefer-source` do exactly that?

**Comment by dnsl48** [comment]
It does. Although not exactly that, because it doesn't find the merge base, but rather simply pulls the tagged commits. In case of recipes that includes some composer updates that we usually don't merge into minors (so they usually don't end up in the following releases).
On the other hand, I think we'd like to keep working with a preexisting release plan and I'm not sure how to make `create-project` revert an existing project to a tagged version.

**Comment by dnsl48** [comment]
Such a new command would also be addressing that issue https://github.com/silverstripe/cow/issues/130

**Comment by ScopeyNZ** [comment]
I think this is mostly possible already by creating a project from the right minor base, copying the `.cow.pat.json` from the prior release, updating the recipe releases with new version numbers, and then applying the patch locally to whatever module for release.

I'd probably feel more comfortable with having a `release:create --from-tag` or something rather than a new command for it.

**Comment by dnsl48** [comment]
> I'd probably feel more comfortable with having a release:create --from-tag or something rather than a new command for it.

Yeah, I was contemplating this approach too, but then it felt to be increasing complexity of the existing functionality (commands). Making it a decoupled command feels more flexible and robust (the *nix way).

> I think this is mostly possible already by creating a project from the right minor base, copying the .cow.pat.json from the prior release, updating the recipe releases with new version numbers, and then applying the patch locally to whatever module for release.

True. On the other hand, automation of the manual routines is the main purpose of COW :)
