### ISSUE TITLE
Increase test coverage on Steps

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/cow#162]
As of the creation of this issue, the current code coverage on Cow is hovering around 25%. For a tool that is responsible for producing accurate Silverstripe releases, this is uncomfortably low.

A primary area of the codebase that is lacking tests is the Steps themselves, and with (somewhat) good reason - this is likely the hardest area to write tests for. Most steps require mocking multiple layers of objects, and the classes in need of mocking don't lend themselves to the process.

This should change. We could spend the time and produce a bulletproof mock set that can be used as a base for testing each Step, refactoring the underlying classes in the process if necessary. Alternatively, we could explore a new test harness that tests the artefacts produced by running the steps in a real environment.

**Comment by dnsl48** [comment]
I suggest we:
 * upgrade PHPUnit to the latest version
 * consider BDD approach (it may be more appropriate for covering steps and their expected outcomes)
 * if not BDD, then we should write generic mocks and reusable fixtures before we improve coverage

**Comment by GuySartorelli** [comment]
We're not going to spend time improving test coverage for cow.
