### ISSUE TITLE
Allow translation outside of a release

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cow#166]
The `release:translate` command is responsible for cycling through all modules to be released, running the i18nTextCollector task against them, and running the Transifex client to push up new keys and pull down translations. It will create commits containing any resulting changes, but will not push them up to GitHub.

One approach we take during release cycles when we want to prepare in advance is analysing changes to modules and tagging them outside of Cow, then using only existing tags in the plan. The downside to this approach is that it stops the translation step from having any effect.

It would be useful to be able to pre-emptively, and separately to tagging / releasing, perform translation updates and push them to GitHub for one or more modules. This would still require creating a release folder in order to make the modules available to translate.

**Comment by robbieaverill** [comment]
Is this not what the translate command does?

**Comment by emteknetnz** [comment]
@Cheddam ?

**Comment by dnsl48** [comment]
> Is this not what the translate command does?

Yes, but it doesn't push the translation commits upstream. We may need an extra command to push all modules without tagging them.

**Comment by Cheddam** [comment]
I've updated the description with some more context.

**Comment by GuySartorelli** [comment]
Done separately now
