### ISSUE TITLE
Improve Docker performance when running on macOS host

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/cow#175]
We've shifted to running Cow through a Docker container. This was primarily tested on Linux hosts, where Docker is a native feature. However, Docker on macOS is driven by a VM, and has significantly different performance characteristics, especially when it comes to disk access. As a result, Cow is unbearably slow when attempting to generate a new release via the Docker instance on macOS, as this operation is extremely I/O-heavy.

There are multiple methods to improve I/O performance when running under macOS, including NFS mounts and [docker-sync](http://docker-sync.io). We should review the available methods and adopt one, aiming to minimise any additional configuration overhead for Cow users both on macOS and other platforms.

#### ACs

- [ ] Performance when running Cow through Docker on macOS is comparable to running it on Linux
- [ ] (Stretch goal) No additional configuration or set-up by the user is required
- [ ] Users on other platforms (Linux / Windows) can still use Cow through Docker as before

#### Metrics
 - release:create 2.6.0 cwp/cwp-recipe-kitchen-sink
   - Linux: 4 minutes
   - macOS (simple bind): 30 minutes
   - macOS (bind with delegated consistency): 24 minutes
   - macOS (bind with cached consistency): 21 minute

**Comment by ScopeyNZ** [comment]
You can probably configure docker using the performance tuning configuration options available in docker: https://docs.docker.com/docker-for-mac/osxfs-caching/

Note that these settings were pretty much added to docker for MacOS. In your case, a `delegated` configuration across the board probably makes sense? It might mean your native FS is significantly behind the VM for a few seconds, but probably doesn't matter for usage of cow.

**Comment by dnsl48** [comment]
I've started tracking the `current` performance for both Linux and macOS. Will be adding to the header of this issue.
The only patch I currently have (which is the difference with current master), I've moved the composer cache into a volume, and not mounting it to the host FS anymore.

P.S. I've had a quick try of `delegated` volume caching, which didn't give me any visible results.
Either I did it wrong, or it didn't help much. Nonetheless, we'll need to investigate that deeper.

**Comment by ScopeyNZ** [comment]
Are you on MacOS now @dnsl48? The configuration I mentioned does nothing on any other platform.

**Comment by dnsl48** [comment]
Yes, I've got an old macOS to debug that thing :)
Though, it's much slower than my Linux PC, so the metrics above are not completely clean, because of the hardware performance differences.

**Comment by dnsl48** [comment]
I suggest we try [Mutagen](https://docs.docker.com/docker-for-mac/mutagen/) next time.

**Comment by emteknetnz** [comment]
Closing as the docker version of cow is no longer being used in practice
