### ISSUE TITLE
Spike: Improve the output and messaging 

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cow#177]
Improve the output and messaging in cow. 

There's a couple of places where cow is signalling it's doing something that it isn't; or it frames output in the wrong place, i.e saying output is erroring when it's not.

- Investigate what's currently happening
  - the worrying error messaging
  - during branching it currently says 'releasing' when that's not actually the case. It leads you to believe it's _publishing_ when it's not
  - always using the verbose flag - should that always happen? Errors should pop up without the verbose flag
- Find areas of improvement
- Address these in the issue, or create new issues for difficult tasks

### Spike
- Note that we're calling this a spike with the aim to identify the issues and look to resolve any quick wins within the same timebox. 

For those issues that you do not get to, please raise new issues.

Timebox: 2 days

**Comment by GuySartorelli** [comment]
This hasn't come up in recent releases - if it is actually a problem that is affecting anyone we can look at re-opening this.
