### ISSUE TITLE
SPIKE: Prior Version no longer calculates correctly, resets when New Version is updated

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cow#179]
https://github.com/silverstripe/cow/issues/174

Run a spike to identify the best path forward or implementation options for the above issue. 

This spike should also end in an estimate of the effort involved.

Options being talked about now:
1. Read the old Cow release plan
2. Check versions from the local git repository
3. Check versions from the remote GitHub repositories
4. Check Packagist API

Timebox: 1 day

**Comment by GuySartorelli** [comment]
If the spike hasn't been done by now it's not likely to. If/when we look at #179 again we can decide if it's worth reopening the spike.
