### ISSUE TITLE
Using the changelog template when a changelog file already exists

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cow#180]
### Overview
A while ago there was [work to create a changelog template](https://github.com/silverstripe/cow/issues/138) that would be used at the time of the release if no changelog file existed.

We've seen this template used a lot for CWP and I think it's been really helpful in keeping clear and concise comms. It could have great benefits for core changelogs too.

However, where this falls over is when a changelog file already exists at the time of preparing the release. Currently in this case (usually always for core) the template can't be used. That's a shame because adding information to the changelog in advance of a release is definitely the right thing to do.

### ACs
- Changelogs for both core and CWP can be created using a template in advance of the release (maybe this is still manual?)
- If a changelog file already exists at the time of the release, amend the file to include the template information

### Notes
- This has come up because I was looking at amending the template to include more information that the changelog refers to a 'recipe release', but this would likely never be used because there's usually a file generated well in advance of the release.
- Draft wording example:
  - ```[If recipe release] This changelog refers to the release of CMS Recipe 4.{x.x}. A full list of module versions included in Recipe 4.{x.x} is provided below. We recommend referencing recipes in your dependencies, rather than individual modules, to simplify version tracking. See [Recipes](https://docs.silverstripe.org/en/4/getting_started/recipes) for more information. (Included module versions in table).```

**Comment by GuySartorelli** [comment]
We have no current plans to implement this change.
