### ISSUE TITLE
Allow release planning with "future" versions of upgrade-only modules

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/cow#182]
# Hypothesis

Planning a release with "future" versions of upgrade-only modules would allow us to co-plan two recipes and then perform sequential `release:publish` for both of them quickly.

# Real life application

Currently, we have to release `CMS Recipe` ahead of beginning the release process for `CWP Recipe`.
With this feature we could plan both `CMS Recipe` and `CWP Recipe` releases simultaneously, and then on the release day we would only need to run `release:publish` for both. That could allow us to couple the `CWP and CMS` releases and prepare CWP release plan before CMS is out.

**Comment by ScopeyNZ** [comment]
Now that the same team manages the whole process, is there a reason to not remove the "upgrade-only" restriction? We only really had that (IIRC) because CWP release management was very much independent of core.

**Comment by dnsl48** [comment]
That's a good point, I didn't think about that. Thanks for chiming in! :)

**Comment by GuySartorelli** [comment]
This is no longer relevant to the current process.
