### ISSUE TITLE
Branching command does not work correctly

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cow#193]
During a release cow broke when it encountered

"graphql": "3.x-dev || 4.x-dev"

Cow said that it needed a caret "^"

Priority wise, it's really not hard to create 30 or so minor branches every 6 months (exactly 29 for CWP 2.7.0-rc1 release), and we need to do this manually for all the 11 non-core recipes any way since they need pull-requests created for their composer.json updates before we could run the cow branching command anyway, so I see fixing this feature as extremely low priority.

**Comment by GuySartorelli** [comment]
Not a problem anymore
