### ISSUE TITLE
Cow occasionally checks out the wrong branches

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/cow#194]
Occasionally cow checkout the wrong branch of some module for no apparent reason. When I did the 4.7.0-rc1 release I got the wrong branch of framework and admin. All the other modules were using the correct branches.

Until we figure out what is going on we can use this simple bash script to figure what branch is module is on.
```bash
#!/usr/bin/env bash
# Run this script from vendor/silverstripe
for f in *; do
    if [ -d "$f" ]; then
        BRANCH=`(cd $f; git rev-parse --abbrev-ref HEAD)`
        printf "%-20s   %s\n" $f $BRANCH
    fi
done
```

**Comment by GuySartorelli** [comment]
This hasn't been a problem for the last however many releases - seems to be fixed
