### ISSUE TITLE
Check Travis build status for branch, fail process if broken or still in progress

### ISSUE THREAD

**Issue by chillu** [silverstripe/cow#2]
Particularly important since the release process doesn't run Behat tests. If we check that a build exists for the current branch SHA, we could even skip the local unit test run and fully rely on Travis.

**Comment by robbieaverill** [comment]
I think in practice this make releasing take a much longer period of time, particularly if you're doing quick hotfixes or merging branches up before release time. Waiting for the CWP kitchen sink recipe (for example) to complete all module builds could potentially block a release for a whole day. It could still be good as a fail safe with a manual override though.

**Comment by Cheddam** [comment]
We also have processes in place to ensure builds are green prior to stable releases, so I don't think Cow needs to get involved here.
