### ISSUE TITLE
Security commits weren't automatically included in changelog

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/cow#209]
During the 4.11.0-rc the changelogs for the security issues weren't automatically included. 

## ACs
- [ ] Changelogs for security issues are correctly included after being cherry-picked in.

**Comment by GuySartorelli** [comment]
I can't reproduce this... @emteknetnz can you please try to reproduce it and either close as unreproducable or add steps to reproduce? It may be something to do with your set up, or the combination/order of commands used, or etc etc to do with your set up or the way you do things, perhaps?

**Comment by emteknetnz** [comment]
Closing, I probably did something wrong.  This functionality has worked in the past and you could not replicate.
