### ISSUE TITLE
Some problems with the translation step

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/cow#210]
During the 4.11.0-beta1 release, several issues were discovered relating to how cow handles translations. These were discussed in the [4.11.0 beta release retro](https://silverstripe.atlassian.net/wiki/spaces/CMS/pages/2644935243/4.11+beta+rc+release+retro).

The problems, raised by @emteknetnz:
- UpdateTranslations::run() - `$this->collectStrings()` should be moved to the top of the `if ($this->doTransifexPullAndUpdate)` conditional block so that it happens before other steps - https://github.com/silverstripe/cow/blob/master/src/Steps/Release/UpdateTranslations.php#L123
- There were textcollector warnings for framework, didn't hurt things in the end, though should be tidied up
- textcollector task doesn't run in cow in my docker env - need to manually run it beforehand, and comment it out in cow.  I have updated confluence with this workaround

You may need to check with him for more details, such as what the warnings were and what triggered them.

## ACs
- [ ] The call to `collectStrings()` is moved to the top of the conditional block
  - [ ] Make sure this _DOES NOT_ cause a regression such as https://github.com/silverstripe/cow/issues/202
- [ ] There are no textcollector warnings for framework

## Stretch goal (there is a workaround so not super important)
- [ ] The textcollector task runs in cow in docker environments.

**Comment by maxime-rainville** [comment]
This is not great, but it's not blocking the 4.11 stable release. Translation is an ongoing problem. We need to disassociate it from release management. We'll do a SPIKE to this affect instead.
