### ISSUE TITLE
Modules added to recipes aren't included in changelogs for their first release

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/cow#227]
If we add a module to a recipe (such as adding silverstripe/developer-docs to recipe-kitchen-sink in 4.12), cow won't want to add changelogs for that module even if you specify a prior version for it.

This is because cow [skips the module if it wasn't in the previous release of the recipe](https://github.com/silverstripe/cow/blob/42449ccc5dd93923776b05eef9ee9d5e30b6c338/src/Steps/Release/CreateChangelog.php#L245-L249) and while it [looks like cow generated the changelog recursively](https://github.com/silverstripe/cow/blob/42449ccc5dd93923776b05eef9ee9d5e30b6c338/src/Steps/Release/CreateChangelog.php#L76-L81) it actually has already generated the full changelog when it loops over kitchen sink, and [skips subsequent libraries](https://github.com/silverstripe/cow/blob/42449ccc5dd93923776b05eef9ee9d5e30b6c338/src/Steps/Release/CreateChangelog.php#L94-L96)

The workaround at the moment is to add a one-off hard-coded line in to explicitly not skip the new module just for this release:
```diff
  $childReleaseName = $childNewReleaseLibrary->getName();
  if (empty($pastComposer['require'][$childReleaseName])) {
+     if (!$childNewRelease->getLibrary()->getName() === 'silverstripe/developer-docs') {
+         continue;
+     }
-     continue;
  }
```

### PRs
- https://github.com/silverstripe/cow/pull/235

**Comment by emteknetnz** [comment]
Note: code above is a little wrong though still works `!$childNewRelease->getLibrary()->getName() ===` doesn't quite make sense

All that's required is to comment out the continue statement;

```
if (empty($pastComposer['require'][$childReleaseName])) {
    // continue;
}

**Comment by GuySartorelli** [comment]
PR merged
