### ISSUE TITLE
Translations not working for 5.0.0-beta1 release

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cow#234]
Note: I don't think we should be running translations during a release, we often seem to have drama.

**We should be doing this outside of releases and raising PRs to the next-minor branches**

I do have tx installed locally

`cow release:translate -vvv --skip-fetch-tags 5.0.0-beta1 silverstripe/recipe-kitchen-sink`

[translations] Pulling sources from transifex for silverstripe/framework (min %10 delta)
  RUN  'find /home/myuser/Releases/release-silverstripe_recipe-kitchen-sink-5.0.0-beta1/vendor/silverstripe/framework/lang -type f \( -name "*.yml" \) -exec touch -t 202202081119.45 {} \;'                             
  ERR  sh: 1: exec: find /home/myuser/Releases/release-silverstripe_recipe-kitchen-sink-5.0.0-beta1/vendor/silverstripe/framework/lang -type f \( -name "*.yml" \) -exec touch -t 202202081119.45 {} \;: not found
  ERR  
  RES  127 Command did not run successfully

## Acceptance criteria
- There's a way to update translations without doing a release e.g. Create a standalone script that does tx pull + tx push (probably as separate command) without using cow
- Pull request are created to update translations ... with an eye to maybe automating the full thing in the long run.
- Does whatever cow does now e.g. runs i18nTextCollectionTask
- Automatically opens pull-requests to the same branch as local using github API
- Runs on recipe-kitchen-sink
- Process is documented so all members of the CMS Squad feel comfortable doing it.
- Update release plan so that translations is no longer done as part of minor release
- Should work across CMS 4 and CMS 5.
- Packagist updated so that `composer install` works

## Out-of-scope
- Design process for the team to run this on a regular basis. (Will be a follow up card)

## Note 
- Need to validate that `tx push` and `tx pull` work for CMS5 branch

## PRs
- https://github.com/silverstripe/silverstripe-tx-translator/pull/2
- https://github.com/silverstripe/gha-generate-matrix/pull/46
- https://github.com/silverstripe/silverstripe-tx-translator/pull/3
- https://github.com/silverstripe/cow/pull/238

**Comment by GuySartorelli** [comment]
relevant:
- https://github.com/silverstripeltd/product-issues/issues/399
- https://github.com/silverstripeltd/product-issues/issues/563

**Comment by GuySartorelli** [comment]
@emteknetnz No PRs linked?

**Comment by emteknetnz** [comment]
Sorry my bad, have linked

**Comment by GuySartorelli** [comment]
We also should have a PR that pulls the translation logic out of cow. We don't want to maintain two sets of this thing.

**Comment by GuySartorelli** [comment]
All done
