### ISSUE TITLE
Some recipe constraints not getting updated

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cow#236]
Recipes such as recipe-collaboration which have "recipe-cms", "recipe-core" or sometimes "framework" had they constraint set to 5.x-dev instead of ~5.0.0@beta

This should have happened during the 'stabilise contstraints' action

This caused used to have to release beta2 for some recipes - example [beta1](https://github.com/silverstripe/recipe-collaboration/commit/a9f9ee5bdac56e18153db2e54d6575576d06c2ef) (wrong) [beta2](https://github.com/silverstripe/recipe-collaboration/commit/329f7dc0734afde13afe8524ec9b0f60add997de) (right)

You can use the new DEV_MODE=1 set in .env in cow to make testing this easier

### ACs
- When stabilizing commits, recipe-collaboration and friends have the correct contraints for recipe-cms/recipe-core/framework
- When destabilizing constraints (~5.0.0@stable => 5.0.x-dev) the contraint is 5.0.0.x-dev, not 5.x-dev

### PRs
- https://github.com/silverstripe/cow/pull/235

**Comment by GuySartorelli** [comment]
PR merged
