### ISSUE TITLE
GitHub token gets output to terminal during publish step

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cow#237]
When running the publish step, the GitHub API token used by composer is output to the terminal

This could lead it to being accidentally shared if someone copy pastes a terminal output

I think this method may be responsible, though I haven't tested to verify

https://github.com/silverstripe/cow/blob/master/src/Utility/Composer.php#L119

## Acceptance criteria
- [x] GitHub token are suppressed from COW output.

## PRs
- https://github.com/silverstripe/cow/pull/244

**Comment by GuySartorelli** [comment]
Donskies
