### ISSUE TITLE
Make developer-docs the first thing processed

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cow#253]
When doing a release, developer-docs should be processed before everything else so that the github workflow to deploy the updated changelog to netlify is run before CI gets bogged down by everything else.

We need the changelog deployed so that we can send out release comms

## Acceptance criteria
- When tagging a release, the changes to the developer-docs are pushed out to GitHub first.

## Note
- We don't have any particular views about how to de this at this stage, it could be a technical or procedural fix or an ugly hack.

## PR
- https://github.com/silverstripe/cow/pull/257

**Comment by GuySartorelli** [comment]
@emteknetnz Please link to all relevant PRs

**Comment by emteknetnz** [comment]
Opps, done

**Comment by GuySartorelli** [comment]
PR merged
