### ISSUE TITLE
Yamlclean produces valid yml that silverstripe doesn't like

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/cow#28]
The below

```yaml
en:
  'NO': 'No'
```

Gets rewritten to:

```yaml
en:
  ? 'NO'
  : 'No'
```

Which is valid yaml, but not a format that silverstripe can read. We use yml spec 1.1, so we need to find a way that cleans up yaml without any incompatibilities.

**Comment by dhensby** [comment]
:(

**Comment by tractorcow** [comment]
I've fixed this over at https://github.com/silverstripe/cow/pull/26 by using symfony/yaml to clean instead.
