### ISSUE TITLE
release:publish doesn't check all modules are available from packagist

### ISSUE THREAD

**Issue by dhensby** [silverstripe/cow#29]
When publishing a release cow checks if the version to be published has been pushed to pacakgist before creating an archive (for publishing to AWS/the SS website).

It does this by checking that silverstripe/installer is available in the required version through composer. However, just because installer is registered with packagist doesn't mean that the other core modules are.

We should check all modules needed for the release are available through composer before proceeding.

**Comment by tractorcow** [comment]
Yes this is a real problem. Once I finish archive step in cow 2.0 I'll make sure to do this properly. :)

**Comment by robbieaverill** [comment]
I must say that I could count the number of times this has been a problem on one hand from my time doing releases at Silverstripe. I agree this would still be a handy check to implement though!

**Comment by Cheddam** [comment]
We have a step in our release process to perform a `composer create-project top-level/recipe test x.x.x` operation immediately after Cow completes its work, so I don't think it's necessary for Cow to manage this.
