### ISSUE TITLE
Process leaves installer on SHA rather than branch

### ISSUE THREAD

**Issue by chillu** [silverstripe/cow#38]
`bin/cow release 4.0.0-alpha4 -vvv --directory /Users/ingo/Sites/4.0.0-alpha4` caused the following error:

![image](https://cloud.githubusercontent.com/assets/111025/22006046/d37518a8-dccc-11e6-8adb-1d437c1b6e30.png)

I've fixed this by manually switching the installer back from a SHA to master.

**Comment by tractorcow** [comment]
Oh of course, the installer repo always ends up on a commit, because of the way composer creates the project.

**Comment by tractorcow** [comment]
Fix is to ensure that `cow project:create` always assigns the installer branch based on the composer constraint used.

**Comment by tractorcow** [comment]
I've tracked this issue to https://github.com/composer/composer/issues/6082

**Comment by tractorcow** [comment]
Fixed with https://github.com/composer/composer/commit/9a26a9e8f82d79e9834605610a8d6cbd4aba6d34 :D Once composer 1.3.2 / 1.4.0 is tagged I'll close this.

**Comment by Cheddam** [comment]
Looks like this is resolved!
