### ISSUE TITLE
git execution doesn't respect git keychain management

### ISSUE THREAD

**Issue by chillu** [silverstripe/cow#40]
I've got a passphrase on my `.ssh/id_rsa` key, which I need to enter at every single authenticated git interaction in `release:publish`, because the git credentials helper doesn't kick in there (https://help.github.com/articles/updating-credentials-from-the-osx-keychain/). Ideally I'd only need to enter the passphrase once

**Comment by tractorcow** [comment]
I've had this issue, but it was fixed for me with https://github.com/silverstripe/cow/commit/57473780cbbd9e6eb936466ea668df1d3212ce40

**Comment by chillu** [comment]
Given that commit has been in the codebase when I ran it, don't think this fixes it for me.

I've got the following in `~/.gitconfig`:

```
[credential]
	helper = osxkeychain
```

Are you sure that your issue was with SSH key passphrases, or just finding keys in the first place?

**Comment by dhensby** [comment]
It works for me when running `ssh-agent`

**Comment by chillu** [comment]
OK, let's close it - don't have the time to validate, but it might well be specific to my environment.
