### ISSUE TITLE
Private releases

### ISSUE THREAD

**Issue by dhensby** [silverstripe/cow#42]
I've been thinking about how we can better support private releases having done a few now. The main context here is about security releases that need to be constructed in private for testing and then released after testing is complete.

Here's my high level of how it should probably be done:

0. User merges any security releases into relevant branches.
1. User creates a local [Satis ](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#satis) repo which has all the private packages required
2. User follows the release process passing a `--repository` option that points to the local satis repo
3. The user runs the publish command with `--skip-upload` step.

Thist to me is the most simple way to do it with minimal changes to cow and a bit of manual work that will have to be documented, though that's not too bad?

It's either this or we *really* tightly couple to our security repos and make a very complex interactive security release tool.

**Comment by tractorcow** [comment]
I thought that for these reasons it would require a satis repo. Does it require a web server, or can we set a local file as a repository?

**Comment by dhensby** [comment]
I've just done a release using a local satis with no webserver

**Comment by dhensby** [comment]
see #27

**Comment by robbieaverill** [comment]
cc @unclecheese

**Comment by GuySartorelli** [comment]
This hasn't been necessary in recent years.
