### ISSUE TITLE
failed to autoload ChangeLog class

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/cow#5]
Failed on Centos 7

The class name and file `ChangeLog.php` have Log starting with capital letter, while Application loads it with lowercase `log` as `Changelog`:

```
- $commands[] = new Commands\Release\Changelog();
+ $commands[] = new Commands\Release\ChangeLog();
```

Do you use host shared filesystem?

**Comment by tractorcow** [comment]
I think we should standardise on `Changelog`. is that agreeable to you?

**Comment by gregsmirnov** [comment]
yes

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/cow/pull/6
