### ISSUE TITLE
Implement --branch strategy for 2.0

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/cow#53]
In 1.x we could set a specific branch for any release.

With 2.x branches are auto-generated from the numeric version and stability; beta and rc would trigger a branch to `major.minor`.

We need to implement a --branch option with the suggested following options:

 - `major` the release will branch to the `major` version
 - `minor` the release will branch to the `major.minor` version
 - `none` no branching will occur
 - `auto` (default) the release will branch automatically based on current rules.
 
Possibly we should implement auto-aliasing on the new (and prior) branches to avoid errors where two branches are aliased to the same numeric version.

**Comment by tractorcow** [comment]
To confirm; Does this option need to be set per-module, or can it be set on the entire release?

**Comment by dhensby** [comment]
I'd assume it's on the whole release and makes the releases for each of the sub modules that make sense (if they are even needed)

**Comment by sminnee** [comment]
I think the setting can be the same for all modules being managed by cow. As long as it's "major" and not "4".

**Comment by tractorcow** [comment]
Ok, maybe we can try this as a step before anything more complex.

**Comment by sminnee** [comment]
Yeah — simpler is good; if the need for complexity arises we should treat that as a "code smell".

As a general architecture, I think a markdown file that describes 1 or 2 short commands to pass to cow in the various circumstances will be more flexible that a very-locked-down set of business logic hard-coded into cow.

As a specific example the problem with an automation for behaviour of a major release is that they happen every couple of years, which means that there's:

 * little pay-off for the automation investment
 * not that many changes to trial the system in production
 * a high chance that our business rules will change by the next time we use the script

cow's hugely valuable by automating some of the tedium of our releases, such as coordinating operations across a large number of packages, and dealing with the confusing wilderness of language packs.

However, I think it should be more "swiss army knife" and less "mysterious green button" ;-)

**Comment by tractorcow** [comment]
Temporary workaround at https://github.com/silverstripe/cow/pull/57/commits/b77a82b69105b8a84d2a80d33bfbf9b1b829fa1e

It won't branch until stable unless we change the behaviour.
