### ISSUE TITLE
Implement archive and upload for 2.0

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/cow#54]
Relies on https://github.com/silverstripe/silverstripe-framework/issues/6860

Substitute both `cms` and `framework only` releases as separate recipes.

**Comment by chillu** [comment]
@tractorcow Does this block the next beta release once we implemented recipes? I'm not questioning if we should do it, but in case we need a short-notice beta release after we've implemented recipes, would we need this task and https://github.com/silverstripe/cow/issues/53?

Not questioning if we should do this, but: Recipes is the feature (showing earlier in backlog), these cow tasks are a means to an end (ideally later in backlog).

**Comment by tractorcow** [comment]
No but it does mean we need to do this manually. This is necessary for zip / tar archives to be available.

In the case of "short notice" releases, I would suggest that these two issues are necessary to avoid the manual tasks of creating archives, and having to re-patch branches (as @flamerohr did yesterday).

To use the analogy, the car runs, but it needs to have it's oil topped up every trip. :)

You are correct in that this is a task separate to the feature itself.

**Comment by tractorcow** [comment]
Implemented at https://github.com/silverstripe/cow/pull/57
