### ISSUE TITLE
Optimise for lowest common php version

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/cow#65]
Since silverstripe supports php 5.6, we should ensure that downloadable zips optimise for the lowest common denominator.

E.g. in Composer::createProject() we should run this line to temporarily set platform version.

```
composer config platform.php 5.6.0
```

We can pull this from the root composer.json for the project.

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/cow/pull/66

**Comment by robbieaverill** [comment]
I think this is done now - combination of #119 and #66
