### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cow#69]
Yeah I'm gonna be _that guy_.
Cow is a great tool, but composer is not recognised as an executable or batch file.
It seems when the environment is windows, somebody or something attempts to run a command in a brand new environment, instead of the one it's in already (i.e. uses `CMD.exe` instead of `bash`). Although composer is both installed and in my path, it doesn't appear to run all that well (at all) in CMD. I managed to get it working relatively easily by creating a batch file to call php directly on the phar, but the output is... less that ideal (or expected). I fear there may be some other environmental factor I'm missing out on as well that I'll not know about until it's either too late (nearing the end of a release), or far far too late (after a release).

I wonder if renaming (or rather copying) `composer` to `composer.bat` would be sufficient?

Simplistic workaround:
```cmd
@echo off
php %userprofile%\bin\composer %*
```
(yes my `$HOME/bin` equivalent there _is_ in my `%PATH%`)

**Comment by NightJar** [comment]
And then git failed. But that _is_ in my path, and _does_ work from `cmd`.

```cmd
In Repository.php line 560:

  [Gitonomy\Git\Exception\ProcessException]
  Error while running git command:
  "git" "--git-dir" [...]
```

```cmd
  '"git"' is not recognized as an internal or external command,
  operable program or batch file.
```

**Comment by robbieaverill** [comment]
I think the fix here to ensure that you have both `composer` and `git` available in your system path
