### ISSUE TITLE
Use target platform reqs instead of --ignore-platform-reqs

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/cow#80]
At the moment, there are two problems:
 - Installing recipe on a system running php 7.x, where we need to support 5.x, will install modules / third party dependencies that don't support 5.x. This can be fixed by setting the config 'platform' option to specify a target.
 - Attempting to install a recipe which may include module dependencies not currently installed on the host computer will block setp. This can be fixed with `--ignore-platform-reqs`.
 
 Since both of those solutions are mutually exclusive, we can only use one or the other.
 
 A better solution is a per-recipe configurable "platform" option which declares the ideal lowest common denominator for each recipe. This would include a target PHP version, as well as a set of provided platform extensions. This would allow us to simultaneously solve both problems.

## PRs
 - [ ] #119

**Comment by dhensby** [comment]
is `--prefer-lowest` going to be of any help?

**Comment by tractorcow** [comment]
It won't solve the missing ext issue (which we want to ignore many times, when we are just doing checkout and tagging).

**Comment by tractorcow** [comment]
Also, we want the highest supported module version for the lowest supported php version, not the lowest module version. ;)

**Comment by dhensby** [comment]
is this resolved?

**Comment by tractorcow** [comment]
No it's not.
