### ISSUE TITLE
Don't treat "Fixing" as a commit prefix

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cow#86]
Some examples from changelogs in the wild:

```
2017-04-26 1ff6f3f1 ing doArchive (John Milmine)
2017-04-07 41eddfcc ing cms page history controller to use new page id param (Tim Kung)
2017-05-02 2187c160b ing pagination api doc typo (3Dgoo)
```

This happens when the commit messages start with `Fixing ...`.

Pretty low priority, but ideally the regex would match the words it looks for with a space or `:` afterwards, but not another letter.

The same thing would happen with `Fixes ...`

```
2017-02-09 6e2797ffc es for using dblib PDO driver. (Andrew O'Neil)
2016-12-08 dc530c0 es #529 (torleif)
```

**Comment by tractorcow** [comment]
Haha, well. Maybe only remove the prefix IFF the whole prefix is a whole word? It's a problem for prefixes other than just "fixing"

**Comment by tractorcow** [comment]
`fixing bug` => `FIX Fixing bug`
`fix bug` => `FIX bug`

**Comment by robbieaverill** [comment]
PR at #110 

Now we only strip commit prefixes if they match the case, i.e.`FIX Foo` should be stripped but `Fix foo` would not. I've assumed that people who write FIX foo know how cow works, but people who write Fix foo don't so in that case Fix would be part of their description.

Also adds spaces to the end of each regex rule, so `Fixed bar` wouldn't end up as `ed bar` in the changelog, even though the case check wouldn't match it anyway
