### ISSUE TITLE
Add ability to customise the "previous tag"

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cow#87]
Currently cow assumes the previous tag based on existing tags.

If we were able to customise it in the plan then we could theoretically provide more power in changelog generation. For example, if I release a tag in a module independently of a cow core release, that tag gets picked up as an existing tag and may not be included in the changelogs. If I could tell cow that the previous tag was 1.2.3 and the new one is 1.2.4, even if both tags exist, the changelog could then include those changes.

**Comment by tractorcow** [comment]
You could but it's a huge amount of work to do that manually for each recipe release (plus a lot of code).

I would look at https://github.com/silverstripe/cow/issues/67 instead as a solution. What you want is a list of PRs that match a date range as well as exist in the release branch. By not using a date range we ended up with commits merged up from prior releases, even if duplicates.

**Comment by robbieaverill** [comment]
Fair call, that looks like a better solution!

**Comment by robbieaverill** [comment]
I'm reopening this because we'd like to get it done now to ensure we have more flexibility in the changelog generation process. Replacing it (#67) would still be a great option, but this would be a short term solution for the problem as well.

**Comment by robbieaverill** [comment]
PR at #104
