### ISSUE TITLE
Publishing silverstripe/installer recipe doesn't seem to work

### ISSUE THREAD

**Issue by dhensby** [silverstripe/cow#91]
Cow v2.1.1 gave me this output when trying to publish release 3.7.1:

```
# cow release:publish 3.7.1 silverstripe/installer -vvv
[publish] Running release of all modules
[publish] All releases published
[wait] No recipes configured for archive
[release:archive] No recipes configured for archive
[upload] No recipes configured for archive
```

This failed to publish the release (make the tag, push the tag, create the archive, upload the archive.

**Comment by robbieaverill** [comment]
Next time somebody does a core release it'd be interesting to see if this is still happening

**Comment by tractorcow** [comment]
Did you miss the `.cow.json` file in your project? Was it added to `.gitignore` or did you change install requirements to prefer-dist so that it excluded the important meta file? Maybe it was a symptom of messing around with the `composer create / install` commands you used to install the project?

**Comment by robbieaverill** [comment]
I'm gonna close for now, we've done core releases since this and it's worked
