### ISSUE TITLE
transifex v0.13 erroneously fails checkTransifexVersion

### ISSUE THREAD

**Issue by dhensby** [silverstripe/cow#92]
Cow is unable to parse the version of transifex from `tx --version` in v0.13 because it is now written to the stderr instead of stdout. (See https://github.com/transifex/transifex-client/issues/239)

Also, the format of the version output has changed from:

```diff
-0.12.4
+0.13.4, py 2.7, x86_64
```

So the parser needs to be updated to support this output signature

**Comment by robbieaverill** [comment]
@scopeynz didn’t you find this too? I feel like you fixed it?

**Comment by ScopeyNZ** [comment]
I attempted to, but my fix didn't work. This was for the 1.9.0-rc1 and we skipped translations in the end I think.

**Comment by ScopeyNZ** [comment]
I'm happy with that. It doesn't seem very likely that someone would accidentally install a version that's a few years old.

**Comment by dhensby** [comment]
agreed - and we make no checks on any other dependencies (such as aws-cli).

**Comment by robbieaverill** [comment]
PR at #100
