### ISSUE TITLE
Dependencies marked as "upgrade-only" are not included in changelogs

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cow#96]
My setup:

* cwp-recipe-kitchen-sink
  * cwp-installer (recipe)
    * cwp-recipe-cms
      * cwp-recipe-core

When I generate a changelog I get (for example):

```
[changelog] Generating changelog content for all releases in this plan
[changelog] Generating changelog for library cwp/cwp-installer (2.0.1 to 2.1.0-rc1)
[changelog] Found changes in 31 modules:
[changelog]  * cwp/cwp-installer from 2.0.1 to 2.1.0-rc1
[changelog]  * cwp/cwp-recipe-core from 2.0.1 to 2.1.0-rc1
[changelog]  * silverstripe/recipe-core from 1.1.1 to 4.2.0
[changelog]  * cwp/cwp-core from 2.0.1 to 2.1.0-rc1
[changelog]  * cwp/cwp-recipe-cms from 2.0.1 to 2.1.0-rc1
[changelog]  * silverstripe/recipe-cms from 1.1.1 to 4.2.0
[changelog]  * cwp/cwp from 2.0.1 to 2.1.0-rc1
[changelog]  * silverstripe/recipe-blog from 1.0.0 to 1.1.0-rc1
[changelog]  * silverstripe/blog from 3.1.0 to 3.2.0
[changelog]  * silverstripe/comments from 3.1.1 to 3.1.2
[changelog]  * silverstripe/recipe-form-building from 1.0.0 to 1.1.0-rc1
[changelog]  * silverstripe/userforms from 5.0.2 to 5.2.0
[changelog]  * silverstripe/recipe-authoring-tools from 1.0.0 to 1.1.0-rc1
[changelog]  * silverstripe/spellcheck from 2.0.2 to 2.1.0
[changelog]  * silverstripe/tagfield from 2.0.0 to 2.1.0
[changelog]  * silverstripe/taxonomy from 2.0.0 to 2.0.1
[changelog]  * silverstripe/recipe-collaboration from 1.0.0 to 1.1.0-rc1
[changelog]  * silverstripe/contentreview from 4.0.1 to 4.1.0
[changelog]  * symbiote/silverstripe-advancedworkflow from 5.0.6 to 5.0.7
[changelog]  * silverstripe/recipe-reporting-tools from 1.0.0 to 1.1.0-rc1
[changelog]  * silverstripe/securityreport from 2.0.0 to 2.0.1
[changelog]  * silverstripe/sitewidecontent-report from 3.0.1 to 3.0.2
[changelog]  * cwp/cwp-recipe-search from 2.0.1 to 2.1.0-rc1
[changelog]  * silverstripe/fulltextsearch from 3.2.0 to 3.3.0
[changelog]  * symbiote/silverstripe-queuedjobs from 4.1.1 to 4.2.2
[changelog]  * silverstripe/recipe-services from 1.0.0 to 1.1.0-rc1
[changelog]  * silverstripe/restfulserver from 2.0.3 to 2.1.0
[changelog]  * tractorcow/silverstripe-fluent from 4.0.2 to 4.1.3
[changelog]  * silverstripe/registry from 2.0.1 to 2.1.0
[changelog]  * cwp/starter-theme from 2.0.0 to 2.0.1
```

## Expected result
Note the line saying `silverstripe/recipe-core from 1.1.1 to 4.2.0` - I'd expect this to include all changes in the recipe-core _modules_ between 1.1.1 and 4.2.0 (1.2.0).

This doesn't include any commits from framework, CMS etc. It's looking at the silverstripe/recipe-cms though.

## Notes for the solution
- We'd like modules marked as 'upgrade-only' to be **optionally enabled** to be included in the changelogs of certain releases.
- Ensure that other functionality tied to the 'upgrade-only' option, like not including further information in the plan, or tagging new versions, remain.
- The place where this becomes a problem, is where we do a CWP release. The changelog will include all commits from the CWP recipes, but not the core recipes (which we want too).

**PRs**

- [ ] #159

**Comment by robbieaverill** [comment]
This could be #87 manifesting itself actually, since it's detecting the core releases as existing tags (which is true) - perhaps not picking up any changes between them.

**Comment by tractorcow** [comment]
Just another symptom of "git log is terrible for changelogs". All of these issues should be grouped together and addressed with a new changelog generator.

**Comment by robbieaverill** [comment]
I think we can fix this somehow, in combination with #87

**Comment by robbieaverill** [comment]
So this happens when recipes are marked as upgrade-only, e.g. `silverstripe/recipe-core`. If you remove that config from cwp/cwp-recipe-cms and cwp/cwp-recipe-core for example, they are included in the changelogs.

**Comment by brynwhyman** [comment]
I've updated the description to add some more information around the expected result.
