### ISSUE TITLE
Changelog includes commits released on previous minor branch already

### ISSUE THREAD

**Issue by chillu** [silverstripe/cow#97]
Compare https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/04_Changelogs/beta/4.2.0-beta1.md with https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/04_Changelogs/4.1.2.md.

Both of them include a commit as the first item (https://github.com/silverstripe/silverstripe-framework/commit/19fdebfa245506626561bc9626d9ac325acb14da) which was released with 4.1.2. So it shouldn't show up in the 4.2.0-beta1 changelog again. This is particularly high impact when it includes security releases, because it gives the false impression that users are getting security fixes (increasing their priority to upgrade), when they in fact might already have those security fixes in their project.

This is probably because the changelog does a diff via `4.1.0...4.2.0-beta1`, rather than `4.1.<latest>...4.2.0-beta1`.

**Comment by robbieaverill** [comment]
Yeah so a bug that you pointed out at the end there with not assuming the latest version correctly (how can you really assume it).

This could be fixed by #87 too, although I do agree with @tractorcow that it would add more work for the cow user. It still adds more flexibility too though.

**Comment by dhensby** [comment]
why can't cow figure out the previous release more accurately?

**Comment by tractorcow** [comment]
The bug is with the way that git log works. If you can fix the issue with git log commands you can port it to cow easily. it's not a cow specific issue.

**Comment by GuySartorelli** [comment]
We've since decided that commits in patches _should_ be included in the changelog - the changelog is effectively showing what has changed _since the previous changelog_.
